apiVersion: v1 
kind: Pod 
metadata: 
    name: dockershell
spec: 
    containers: 
      - name: docker-cmds 
        image: docker:17.03.1-ce
        command: ['sleep', '3600' ] 
        volumeMounts: 
          - mountPath: /var/run 
            name: docker-sock 
    volumes: 
      - name: docker-sock 
        hostPath: 
            path: /var/run 
