---
apiVersion: v1
kind: Service
metadata:
  name: invokator
  labels:
    run: invokator
spec:
  type: NodePort
  selector:
    name: invokator
  ports:
  - protocol: TCP
    nodePort: 30700
    port: 7000
    name: invokator

