---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    run: monitor
spec:
  type: NodePort
  selector:
    name: monitor
  ports:
  - protocol: TCP
    nodePort: 30701
    port: 7001
    name: monitor

